name: Reset schedule

on:
  schedule:
    - cron: '0 7 * * 0' # 매주 일요일 16시
  workflow_dispatch:

jobs:
  reset-schedule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Reset schedule
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: pnpm ts-node scripts/reset-schedule.ts
