name: Reset schedule

on:
  schedule:
    - cron: '0 7 * * 0' # 매주 일요일 16시
  workflow_dispatch:

jobs:
  reset-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Approve PNPM builds
        run: pnpm approve-builds

      - name: Reset schedule
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "=== Starting RTDB reset script ==="
          pnpm exec tsgo scripts/reset-schedule.ts
          echo "=== Finished RTDB reset script ==="
